# Generated by Django 6.0.6 on 2026-07-02 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn', models.CharField(choices=[('W', 'White'), ('B', 'Black')], default='W', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('M', 'Checkmate'), ('S', 'Stalemate')], default='A', max_length=1)),
                ('winner', models.CharField(blank=True, choices=[('W', 'White'), ('B', 'Black')], default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(choices=[('P', 'Pawn'), ('N', 'Knight'), ('B', 'Bishop'), ('R', 'Rook'), ('Q', 'Queen'), ('K', 'King')], max_length=1)),
                ('color', models.CharField(choices=[('W', 'White'), ('B', 'Black')], max_length=1)),
                ('file', models.PositiveSmallIntegerField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('is_captured', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('W', 'White'), ('B', 'Black')], max_length=1)),
                ('piece_type', models.CharField(choices=[('P', 'Pawn'), ('N', 'Knight'), ('B', 'Bishop'), ('R', 'Rook'), ('Q', 'Queen'), ('K', 'King')], max_length=1)),
                ('from_file', models.PositiveSmallIntegerField()),
                ('from_rank', models.PositiveSmallIntegerField()),
                ('to_file', models.PositiveSmallIntegerField()),
                ('to_rank', models.PositiveSmallIntegerField()),
                ('captured_type', models.CharField(blank=True, choices=[('P', 'Pawn'), ('N', 'Knight'), ('B', 'Bishop'), ('R', 'Rook'), ('Q', 'Queen'), ('K', 'King')], default='', max_length=1)),
                ('promoted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='core.game')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
