# Generated by Django 6.0.6 on 2026-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='castled',
            field=models.BooleanField(default=False),
        ),
    ]
